

let num1 = 50 , num2 = 2;

try {
    console.log(num1/num2);
    console.log(a);
} catch(err){
 console.log(err.message);
} finally {
    console.log("Finally Executed.");
}